[package]
name = "fa2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive", "env"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
